title: Kiddo Go - For Parents on the Go
logo: /assets/img/logo.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
base url: /kiddogo
url: https://achigbrow.github.io
theme: jekyll-theme-minimal

